### ISSUE TITLE
请问一下我在amgame下make的时候会报这个错误呢，是什么配置错误了吗，下面是报错信息

### ISSUE THREAD

**Issue by yboi1** [NJU-ProjectN/os-workbench-2022#10]
(base) [boyi@boyi amgame]$ make
# Building amgame-image [x86_64-qemu]
# Building am-archive [x86_64-qemu]
+ CC src/x86/qemu/ioe.c
/home/boyi/Code/Systerm/os-workbench-2022/abstract-machine/am/src/x86/qemu/ioe.c: 在函数‘__am_lapic_bootap’中:
/home/boyi/Code/Systerm/os-workbench-2022/abstract-machine/am/src/x86/qemu/ioe.c:433:6: 错误：array subscript 0 is outside array bounds of ‘uint16_t[0]’ {或称 ‘short unsigned int[]’} [-Werror=array-bounds=]
  433 |   wrv[0] = 0;
      |   ~~~^~~
cc1: 附注：source object is likely at address zero
/home/boyi/Code/Systerm/os-workbench-2022/abstract-machine/am/src/x86/qemu/ioe.c:434:6: 错误：array subscript 0 is outside array bounds of ‘uint16_t[0]’ {或称 ‘short unsigned int[]’} [-Werror=array-bounds=]
  434 |   wrv[1] = (uintptr_t)addr >> 4;

**Comment by sashimi-yzh** [comment]
试试 https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105523#c1

**Comment by sashimi-yzh** [comment]
可参考 https://github.com/NJU-ProjectN/abstract-machine/commit/0e37b474981568f2790f75f5d1105bbb2509515c 修复该问题
